### ISSUE TITLE
Why is MultiplePsiFilesPerDocumentFileViewProvider used?

### ISSUE THREAD

**Issue by donnerpeter** [PioBeat/GravSupport#3]
https://github.com/PioBeat/GravSupport/blob/f4b8e4ed8548573ac16c1241fd418a6d7efb6b3b/src/net/offbeatpioneer/intellij/plugins/grav/treestructure/LanguageFileViewProvider.java#L16

There don't seem to be any any multiple roots defined here (and after API changes in 173 this won't compile). I'd suggest to use SingleRootFileViewProvider instead.

**Comment by PioBeat** [comment]
Thanks for raising this issue. I was targeting only 172 yet but will check this out and fix it.
